### ISSUE TITLE
API suggestions: new Stack() - and allow new Stack(a,b, c) initial values

### ISSUE THREAD

**Issue by kristianmandrup** [avoidwork/tiny-stack#2]
Would be nice if we could do `new Stack()` which follows conventions
Could we also please have the constructor optionally take stack initial values as optional argument :)
Thanks.

**Comment by avoidwork** [comment]
Hi,

I missed this request somehow; it's in 1.1.0!

**Comment by avoidwork** [comment]
btw 2.0.0 removes ES5 transpile
